export function buildReportLabels(
  t: (key: string) => string,
  extra: Record<string, string> = {},
): Record<string, string> {
  const keys = [
    "title",
    "course",
    "class",
    "student",
    "studentCode",
    "period",
    "generatedOn",
    "from",
    "to",
    "teachingSessions",
    "materializedSessions",
    "completedSessions",
    "cancelledSessions",
    "attendanceByLearner",
    "eligibleSessions",
    "present",
    "absent",
    "late",
    "excused",
    "notRecorded",
    "attendanceRate",
    "noLearners",
    "noAssessments",
    "summary",
    "learnersScored",
    "noScoreRecorded",
    "averagePercentage",
    "highestLowest",
    "resultsByLearner",
    "classStatus",
    "enrollmentCount",
    "averageAttendanceRate",
    "assessmentMean",
    "enrollmentStatus",
    "noEnrollments",
    "observations",
    "noObservations",
    "sessionsWithObservations",
    "indicator",
    "rating",
    "count",
    "teacherComments",
    "observationsLimited",
    "attendanceDetail",
    "assessmentDetail",
    "enrollmentContext",
    "enrollmentDates",
    "ongoing",
    "attendance",
    "noAttendance",
    "assessments",
    "assessmentTitle",
    "assessmentDate",
    "score",
    "percentage",
    "progressSummary",
    "progressSummaryNote",
    "applyPeriod",
    "reportingPeriod",
    "invalidPeriod",
    "deniedAttendance",
    "deniedAssessment",
    "deniedProgress",
    "hubSubtitle",
    "attendanceReport",
    "assessmentReport",
    "endOfCourseReport",
    "learnerProgressReport",
    "backToReports",
    "backToClasses",
    "backToEnrollments",
    "print",
    "selectEnrollment",
    "allHistory",
  ] as const;

  const labels: Record<string, string> = {};
  for (const key of keys) {
    labels[key] = t(key);
  }
  return { ...labels, ...extra };
}
